In [117]:
import numpy as np
import sympy
import math
from sympy import *
from sympy.matrices import Matrix
from math import hypot

In [122]:
def function(x1, y1, z1, x2, y2, z2, x3, y3, z3):
    r1=(x3-x1, y3-y1, z3-z1)
    r2=(x2-x1, y2-y1, z2-z1)
    r3=(x2-x3, y2-y3, z2-z3)
    R1=((x3-x1)**2+(y3-y1)**2+(z3-z1)**2)**0.5
    R2=((x2-x1)**2+(y2-y1)**2+(z2-z1)**2)**0.5
    R3=((x2-x3)**2+(y2-y3)**2+(z2-z3)**2)**0.5
    a1=np.array(r1)
    b1=np.array(r2)
    c1=R3*np.dot(a1,b1)
    a2=np.array(r2)
    b2=np.array(r3)
    c2=R1*np.dot(a2,b2)
    a3=np.array(r3)
    b3=np.array(r1)
    c3=R2*np.dot(a3,b3)
    l=R1*R2*R3
    return r1, r2, r3, R1, R2, R3, c1, c2, c3, l

In [123]:
function(1, 2, 40, 2, 5, 9, 1, 7, 5)

((0, 5, -35),
 (1, 3, -31),
 (1, -2, 4),
 35.35533905932738,
 31.160872901765767,
 4.58257569495584,
 5040.833264451424,
 -4560.838738653231,
 -4674.130935264865,
 5048.638430309701)

In [107]:
A = np.matrix('0,5,35; 1,3,-31; 1,-2,4')
print(A)

[[  0   5  35]
 [  1   3 -31]
 [  1  -2   4]]


In [111]:
u=np.linalg.det(A)
u

-350.00000000000017

In [114]:
def telesniy_ugol(u,l,c1,c2,c3):
    w=2*atan(u/(l+c1+c2+c3))
    return w

In [115]:
telesniy_ugol(-350, 5048, 5040, 4560, 4674)

-0.0362241721287423

In [79]:
def function(x1, y1, z1, x2, y2, z2, x3, y3, z3):
    r1=(x3-x1, y3-y1, z3-z1)
    r2=(x2-x1, y2-y1, z2-z1)
    r3=(x2-x3, y2-y3, z2-z3)
    R1=((x3-x1)**2+1y3-y1)**2+(z3-z1)**2)**0.5
    R2=((x2-x1)**2+(y2-y1)**2+(z2-z1)**2)**0.5
    R3=((x2-x3)**2+(y2-y3)**2+(z2-z3)**2)**0.5
    a1=np.array(r1)
    b1=np.array(r2)
    c1=R3*np.dot(a1,b1)
    a2=np.array(r2)
    b2=np.array(r3)
    c2=R1*np.dot(a2,b2)
    a3=np.array(r3)
    b3=np.array(r1)
    c3=R2*np.dot(a3,b3)
    return r1, r2, r3, R1, R2, R3, c1, c2, c3
a4=np.array([1,2,3])
a4=np.append(a4,[10,20,30])
m=Matrix()

array([ 1,  2,  3, 10, 20, 30])

In [94]:
a4=np.array([1,2,3])
b4=np.array([10,20,30])
m=np.linalg.det()
    u=-350
    l=5048.638430309701
    c1=5040.833264451424
    c2=-4560.838738653231
    c3=-4674.130935264865,

TypeError: _unary_dispatcher() missing 1 required positional argument: 'a'

In [95]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [116]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = (1, 11, 12)
P1 = (2, 12, 22)
p  = (3, 13, 23)
print(distance(P0, P1, p))

TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

In [92]:
a4=np.array([1,2])
a4=np.append(a4,[10,20,30])
m=Matrix()
m.det()

1

In [87]:
m.det()

AttributeError: 'numpy.ndarray' object has no attribute 'det'

In [85]:
m

Matrix([
[0, -3, 35],
[1, -5, 31],
[1, -2,  4]])

In [74]:
m.det()

24

In [ ]:
def telesniy_ugol():
    w=2*atan((m.det()/(R1*R2*R3+c1+c2+c3))
    return

In [53]:
def function2(x1, y1, z1, x2, y2, z2, x3, y3, z3):
    r1=(x3-x1, y3-y1, z3-z1)
    r2=(x2-x1, y2-y1, z2-z1)
    r3=(x2-x3, y2-y3, z2-z3)
    a1=np.array(r1)
    b1=np.array(r2)
    c1=np.dot(a1,b1)
    a2=np.array(r2)
    b2=np.array(r3)
    c2=np.dot(a2,b2)
    a3=np.array(r3)
    b3=np.array(r1)
    c3=np.dot(a3,b3)
    return c1, c2, c3

In [54]:
function2(5, 8, 4, 2, 5, 9, 1, 7, 5)

(40, 23, 2)

In [34]:
def function3(x1, y1, z1, x2, y2, z2, x3, y3, z3):
    r1=(x3-x1, y3-y1, z3-z1)
    r2=(x2-x1, y2-y1, z2-z1)
    r3=(x2-x3, y2-y3, z2-z3)
    R1=((x3-x1)**2+(y3-y1)**2+(z3-z1)**2)**0.5
    R2=((x2-x1)**2+(y2-y1)**2+(z2-z1)**2)**0.5
    R3=((x2-x3)**2+(y2-y3)**2+(z2-z3)**2)**0.5
    tetta1=acos((R1**2+R2**2-R3**2)/(2*R1*R2))
    tetta2=acos((R3**2+R2**2-R1**2)/(2*R3*R2))
    tetta3=acos((R1**2+R3**2-R2**2)/(2*R3*R1))
    d1=R1*R2*tetta1
    d2=R2*R3*tetta2
    d3=R1*R3*tetta3
    return tetta1, tetta2, tetta3, d1, d2, d3

In [35]:
function(9, 8, 7, 6, 5, 4, 3, 2, 1)

((-6, -6, -6),
 (-3, -3, -3),
 (3, 3, 3),
 10.392304845413264,
 5.196152422706632,
 5.196152422706632,
 0,
 3.14159265358979,
 0,
 0,
 84.8230016469244,
 0)

In [36]:
def function3(x1, y1, z1, x2, y2, z2, x3, y3, z3):
    r1=(x3-x1, y3-y1, z3-z1)
    r2=(x2-x1, y2-y1, z2-z1)
    r3=(x2-x3, y2-y3, z2-z3)
    R1=((x3-x1)**2+(y3-y1)**2+(z3-z1)**2)**0.5
    R2=((x2-x1)**2+(y2-y1)**2+(z2-z1)**2)**0.5
    R3=((x2-x3)**2+(y2-y3)**2+(z2-z3)**2)**0.5
    tetta1=acos((R1**2+R2**2-R3**2)/(2*R1*R2))
    tetta2=acos((R3**2+R2**2-R1**2)/(2*R3*R2))
    tetta3=acos((R1**2+R3**2-R2**2)/(2*R3*R1))
    d1=R1*R2*tetta1
    d2=R2*R3*tetta2
    d3=R1*R3*tetta3
    m=Matrix([[1, 2, 7], [2, 3, 1], [2, 4, 6]])
    return tetta1, tetta2, tetta3, d1, d2, d3

In [37]:
m=Matrix([[1, 2, 7], [2, 3, 1], [2, 4, 6]])

In [38]:
m1=Matrix([[(x3-x1, y3-y1, z3-z1)], [(x2-x1, y2-y1, z2-z1)], [x2-x3, y2-y3, z2-z3]])

NameError: name 'x3' is not defined

In [96]:
def function4(x1, y1, z1, x2, y2, z2, x3, y3, z3):
    r1=(x3-x1, y3-y1, z3-z1)
    r2=(x2-x1, y2-y1, z2-z1)
    r3=(x2-x3, y2-y3, z2-z3)
    m2=Matrix([[r1], [r2], [r3]])
    return r1, r2, r3, m2

In [97]:
function4(9, 8, 7, 6, 5, 4, 3, 2, 1)

((-6, -6, -6),
 (-3, -3, -3),
 (3, 3, 3),
 Matrix([
 [(-6, -6, -6)],
 [(-3, -3, -3)],
 [   (3, 3, 3)]]))

In [125]:
A = [1, 2, 1]
B = [2, 5, 7]
D = [40, 9, 5]
lenr1 = math.sqrt( ((B[0]-A[0])**2)+((B[1]-A[1])**2)+(B[2]-A[2])**2)
lenr2 = math.sqrt( ((D[0]-A[0])**2)+((D[1]-A[1])**2)+(D[2]-A[2])**2)
lenr3 = math.sqrt( ((D[0]-B[0])**2)+((D[1]-B[1])**2)+(D[2]-B[2])**2)
print(lenr1, lenr2, lenr3)

6.782329983125268 39.824615503479755 38.262252939417984


In [ ]:
1, 2, 40, 2, 5, 9, 1, 7, 5